// react-client/src/components/RouterView.js
import { Routes, Route } from "react-router-dom";
import Login from '../pages/Login';
import Register from '../pages/Register';
import React from 'react';



export default function RouterView() {
  return (
    <Routes>
      <Route path="/login" element={<Login />} />
      <Route path="/register" element={<Register />} />
    </Routes>
  )
}

// svelte/src/lib/RouterView.svelte
<script>
// @ts-nocheck
  import { Router, Route } from "svelte-routing";
  import Dashboard from '../pages/Dashboard.svelte';
  import Login from '../pages/Login.svelte';

  export let url = "";
</script>

<Router url="{url}">
  <Route path="/dashboard">
    <Dashboard />
  </Route>
  <Route path="/login">
    <Login />
  </Route>
</Router>
